# Generated by Django 3.2.4 on 2021-06-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_profilechanges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechanges',
            name='change_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profilechanges',
            name='next_state',
            field=models.CharField(choices=[('PAP', 'Pending Approval'), ('PAS', 'Pending Assumption'), ('APP', 'Approved'), ('REJ', 'Rejected'), ('NEW', 'Just registered')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profilechanges',
            name='prev_state',
            field=models.CharField(choices=[('PAP', 'Pending Approval'), ('PAS', 'Pending Assumption'), ('APP', 'Approved'), ('REJ', 'Rejected'), ('NEW', 'Just registered')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_status',
            field=models.CharField(choices=[('PAP', 'Pending Approval'), ('PAS', 'Pending Assumption'), ('APP', 'Approved'), ('REJ', 'Rejected'), ('NEW', 'Just registered')], default='NEW', max_length=3),
        ),
    ]
